name: Pipeline

on:
    pull_request:
    push:
        branches: ["*"]

jobs:
    publish:
        name: Publish to Docker Hub
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Extract project metadata
              env:
                  AUTHOR: ${{ vars.DOCKER_HUB_USERNAME }}
                  GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
              run: |
                  declare -a split_by_slash=()

                  IFS="/" read -ra split_by_slash <<< "$GITHUB_REPOSITORY"

                  REAL_AUTHOR=${AUTHOR:-${split_by_slash[0]}}

                  echo "AUTHOR=$REAL_AUTHOR" >> "$GITHUB_ENV"
                  echo "TAG=$REAL_AUTHOR/shell-devcontainer" >> "$GITHUB_ENV"

            - uses: docker/setup-buildx-action@v3
              name: Setup Docker Buildx

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ env.AUTHOR }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Publish Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ env.TAG }}

